(() => {

    const filters=[...document.querySelectorAll('.filter')],games=[...document.querySelectorAll('.game')];
    filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));btn.classList.add('active');games.forEach(g=>g.classList.toggle('hidden',btn.dataset.filter!=='all'&&g.dataset.category!==btn.dataset.filter))}));
    const modal=document.querySelector('#modal'),toast=document.querySelector('#toast'),tankFrame=document.querySelector('#tankFrame');let toastTimer,opener;
    const announceModal=open=>{if(typeof window.CustomEvent==='function')document.dispatchEvent?.(new window.CustomEvent('arcade:modal',{detail:{open}}))};
    const background=document.querySelector('.wrap');
    games.forEach(card=>card.querySelector('.play').addEventListener('click',()=>{opener=card.querySelector('.play');document.querySelector('#modalTitle').textContent=card.dataset.title;document.querySelector('#modalText').textContent=card.dataset.description;const isRace=card.dataset.title==='Vice City Race',isQuiz=card.dataset.title==='Легенда или слух?',isChase=card.dataset.title==='Chase Me',isDuo=card.dataset.title==='Дело на двоих',isSun=card.dataset.title==='После заката',isWarehouse=card.dataset.title==='Последняя доставка',isTanks=card.dataset.title==='Neon Tanks';document.querySelector('#tankGame').hidden=!isTanks;modal.classList.toggle('tank-mode',isTanks);if(isTanks)tankFrame.src='neon-tanks.html';else tankFrame.src='about:blank';document.querySelector('#warehouseGame').hidden=!isWarehouse;modal.classList.toggle('warehouse-mode',isWarehouse);WarehouseDefense.stop();if(isWarehouse)WarehouseDefense.open();document.querySelector('#sunGame').hidden=!isSun;modal.classList.toggle('sun-mode',isSun);AfterSunset.stop();if(isSun)AfterSunset.open();document.querySelector('#duoGame').hidden=!isDuo;modal.classList.toggle('duo-mode',isDuo);DuoGame.stop();if(isDuo)DuoGame.open();document.querySelector('#chaseGame').hidden=!isChase;modal.classList.toggle('chase-mode',isChase);ChaseMe.stop();if(isChase)ChaseMe.open();document.querySelector('#raceGame').hidden=!isRace;document.querySelector('#quizGame').hidden=!isQuiz;document.querySelector('#launch').hidden=isRace||isQuiz||isChase||isDuo||isSun||isWarehouse||isTanks;document.querySelector('#modalText').hidden=isRace||isQuiz||isChase||isDuo||isSun||isWarehouse||isTanks;ViceCityRace.stop();if(isRace)ViceCityRace.open();modal.classList.toggle('race-mode',isRace);if(isQuiz)resetQuiz();modal.classList.add('open');document.body?.classList.add('modal-open');if(background)background.inert=true;document.querySelector('.close').focus?.();announceModal(true)}));
    const closeModal=()=>{if(!modal.classList.contains('open'))return;modal.classList.remove('open');document.body?.classList.remove('modal-open');if(background)background.inert=false;ChaseMe.stop();DuoGame.stop();ViceCityRace.stop();AfterSunset.stop();WarehouseDefense.stop();tankFrame.src='about:blank';announceModal(false);opener?.focus?.()};
    document.querySelector('.close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
    document.addEventListener('keydown',e=>{if(!modal.classList.contains('open'))return;if(e.key==='Escape'){e.preventDefault();closeModal();return}if(e.key!=='Tab'||e.defaultPrevented)return;const candidates=[...modal.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),canvas[tabindex]')].filter(el=>el.offsetParent!==null&&!el.closest?.('[hidden]'));if(!candidates.length)return;const first=candidates[0],last=candidates[candidates.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
    document.querySelector('#launch').addEventListener('click',()=>{closeModal();toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)});
    const quizQuestions=[
      {q:'Главные герои истории — Джейсон Дюваль и Люсия Каминос.',a:'confirmed',why:'Да. Rockstar представила Джейсона и Люсию как центральных персонажей.',url:'https://www.rockstargames.com/VI/only-in-leonida'},
      {q:'Действие GTA VI развернётся в штате Леонида, включая Вайс-Сити.',a:'confirmed',why:'Подтверждено на официальном сайте: история охватывает Леониду и современный Вайс-Сити.',url:'https://www.rockstargames.com/VI'},
      {q:'Официальная дата выхода игры — 19 ноября 2026 года.',a:'confirmed',why:'Rockstar указывает 19 ноября 2026 года как дату выхода.',url:'https://www.rockstargames.com/VI'},
      {q:'Rockstar подтвердила выход игры на PlayStation 5 и Xbox Series X|S.',a:'confirmed',why:'Эти платформы перечислены на официальном сайте GTA VI.',url:'https://www.rockstargames.com/VI'},
      {q:'Rockstar уже подтвердила версию GTA VI для PC к дате выхода на консолях.',a:'rumor',why:'В официальном списке платформ сейчас указаны PS5 и Xbox Series X|S. Дата PC-версии не объявлена.',url:'https://support.rockstargames.com/articles/4QfG4FmZCf5W1gS8jy4UVT/grand-theft-auto-vi-platform-editions-and-versions-Platforms'},
      {q:'Официальный альбом GTA VI будет включать 34 оригинальных трека.',a:'confirmed',why:'Rockstar сообщила о 34 оригинальных композициях в альбоме, который выйдет вместе с игрой.',url:'https://www.rockstargames.com/newswire/article/7599a881942544/announcing-grand-theft-auto-vi-the-album-coming-november-19'},
      {q:'Rockstar подтвердила, что карта игры будет точной копией всей Флориды.',a:'rumor',why:'Официально подтверждён вымышленный штат Леонида. Заявления о точной копии всей Флориды Rockstar не делала.',url:'https://www.rockstargames.com/VI'},
      {q:'В официальном анонсе Rockstar описывает GTA VI как одиночное приключение.',a:'confirmed',why:'Так игра описана в публикации Rockstar о старте предзаказов.',url:'https://www.rockstargames.com/newswire/article/5171972o3ak5oa/pre-order-grand-theft-auto-vi-on-june-25'},
      {q:'К релизу альбома уже объявили первые шесть синглов.',a:'confirmed',why:'Первые шесть синглов стали доступны вместе с анонсом альбома 17 сентября 2026 года.',url:'https://www.rockstargames.com/newswire/article/7599a881942544/announcing-grand-theft-auto-vi-the-album-coming-november-19'},
      {q:'Rockstar уже назвала все радиостанции и раскрыла полный саундтрек игры.',a:'rumor',why:'Объявлен альбом из 34 треков и первые шесть синглов. Полный список радиостанций Rockstar пока не публиковала.',url:'https://www.rockstargames.com/newswire/article/7599a881942544/announcing-grand-theft-auto-vi-the-album-coming-november-19'}
    ];let quizIndex=0,quizScore=0;
    function resetQuiz(){quizIndex=0;quizScore=0;const q=document.querySelector('#quizGame');q.classList.remove('started','done');document.querySelector('#quizStart').textContent='НАЧАТЬ КВИЗ ↗';document.querySelector('#quizScore').textContent='0';document.querySelector('#quizProgress').textContent='ВОПРОС 1 / 10';document.querySelector('#quizMeter').style.width='10%';document.querySelector('#quizLabel').textContent='ПРАВДА ИЛИ СЛУХ?';document.querySelector('#quizQuestion').textContent='Здесь появится вопрос';document.querySelector('#quizFeedback').textContent='';document.querySelector('#quizSource').hidden=true;document.querySelector('#quizNext').hidden=true;document.querySelectorAll('.quiz-answers button').forEach(b=>{b.disabled=false;b.classList.remove('correct','wrong')})}
    function showQuizQuestion(){const item=quizQuestions[quizIndex];document.querySelector('#quizProgress').textContent=`ВОПРОС ${quizIndex+1} / ${quizQuestions.length}`;document.querySelector('#quizMeter').style.width=`${(quizIndex+1)/quizQuestions.length*100}%`;document.querySelector('#quizLabel').textContent='ПРАВДА ИЛИ СЛУХ?';document.querySelector('#quizQuestion').textContent=item.q;document.querySelector('#quizFeedback').textContent='';document.querySelector('#quizSource').hidden=true;document.querySelector('#quizNext').hidden=true;document.querySelectorAll('.quiz-answers button').forEach(b=>{b.disabled=false;b.classList.remove('correct','wrong')})}
    function beginQuiz(){resetQuiz();document.querySelector('#quizGame').classList.add('started');showQuizQuestion()}
    function answerQuiz(answer){const item=quizQuestions[quizIndex],correct=answer===item.a;if(correct){quizScore++;document.querySelector('#quizScore').textContent=quizScore}document.querySelectorAll('.quiz-answers button').forEach(b=>{b.disabled=true;if(b.dataset.answer===item.a)b.classList.add('correct');else if(b.dataset.answer===answer)b.classList.add('wrong')});document.querySelector('#quizLabel').textContent=correct?'ВЕРНО · '+(item.a==='confirmed'?'ПОДТВЕРЖДЕНО':'ПОКА СЛУХ'):'НЕ СОВСЕМ · '+(item.a==='confirmed'?'ПОДТВЕРЖДЕНО':'ПОКА СЛУХ');document.querySelector('#quizFeedback').textContent=item.why;const source=document.querySelector('#quizSource');source.href=item.url;source.hidden=false;const next=document.querySelector('#quizNext');next.textContent=quizIndex===quizQuestions.length-1?'ИТОГ ↗':'СЛЕДУЮЩИЙ ВОПРОС ↗';next.hidden=false}
    function nextQuiz(){if(quizIndex<quizQuestions.length-1){quizIndex++;showQuizQuestion();return}const q=document.querySelector('#quizGame');q.classList.add('done');q.classList.remove('started');document.querySelector('#quizLabel').textContent='ТВОЙ РЕЗУЛЬТАТ';document.querySelector('#quizQuestion').textContent=`${quizScore} / ${quizQuestions.length}`;document.querySelector('#quizFeedback').textContent=quizScore===10?'Безупречно! Ты отделяешь подтверждённые факты от шума.':quizScore>=7?'Отличный радар. Загляни в источники у ответов, которые удивили.':'Есть что проверить — открой источники Rockstar у ответов и сыграй ещё раз.';document.querySelector('#quizSource').hidden=true;document.querySelector('#quizNext').hidden=true;document.querySelector('#quizStart').textContent='СЫГРАТЬ ЕЩЁ ↗'}
    document.querySelector('#quizStart').addEventListener('click',()=>{if(document.querySelector('#quizGame').classList.contains('done'))beginQuiz();else beginQuiz()});document.querySelectorAll('.quiz-answers button').forEach(b=>b.addEventListener('click',()=>answerQuiz(b.dataset.answer)));document.querySelector('#quizNext').addEventListener('click',nextQuiz);
    const menu=document.querySelector('.menu'),nav=document.querySelector('.nav');
    const closeMenu=()=>{nav.classList.remove('open');menu.setAttribute?.('aria-expanded','false');menu.setAttribute?.('aria-label','Открыть меню')};
    menu.addEventListener('click',()=>{const open=!nav.classList.contains('open');nav.classList.toggle('open',open);menu.setAttribute?.('aria-expanded',String(open));menu.setAttribute?.('aria-label',open?'Закрыть меню':'Открыть меню')});
    nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
    document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus?.()}});
    window.matchMedia?.('(min-width:761px)')?.addEventListener?.('change',e=>{if(e.matches)closeMenu()});
})();
