(() => {
  'use strict';
  const $=id=>document.getElementById(id),game=$('sunGame'),canvas=$('sunCanvas'),ctx=canvas.getContext('2d');
  const map=new Image();map.src='sunset-waterfront.png';map.onload=()=>{if(s)draw()};
  const sites={radio:{x:185,y:250,label:'РАДИО'},keeper:{x:1250,y:255,label:'СМОТРИТЕЛЬ'},fuse:{x:1050,y:240,label:'ПРЕДОХРАНИТЕЛЬ'},battery:{x:295,y:720,label:'АККУМУЛЯТОР'},lens:{x:720,y:235,label:'ЛИНЗА'},pendant:{x:1430,y:855,label:'МЕДАЛЬОН'},lighthouse:{x:1390,y:800,label:'МАЯК'}};
  let s,checkpoint,raf=0,last=0,camera={zoom:1,x:0,y:0};const inputs=new Map();
  const held=action=>[...inputs.values()].includes(action),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  function panel(title,message,button,callback,secondary){
    $('sunPuzzle').hidden=true;$('sunSignal').hidden=true;$('sunOverlay').hidden=false;$('sunTitle').textContent=title;$('sunMessage').textContent=message;$('sunContinue').textContent=button;$('sunContinue').onclick=callback;
    $('sunChoice').hidden=!secondary;if(secondary){$('sunChoice').textContent=secondary.label;$('sunChoice').onclick=secondary.action}
  }
  function halt(){cancelAnimationFrame(raf);inputs.clear();raf=0}
  function stop(){halt();if(s)s.mode='closed'}
  function save(){checkpoint=JSON.parse(JSON.stringify(s));checkpoint.mode='running';checkpoint.time=Math.max(s.time,120);checkpoint.hurt=0}
  function open(){stop();s={mode:'ready',act:0,player:{x:115,y:255,phase:0,moving:false,heading:'front',face:1},elapsed:0,time:240,hp:3,hurt:0,stamina:100,lantern:false,parts:[],pendant:false,promised:false,channels:[0,0,0],pulses:0,needle:.5,signalTime:0,lastPulse:-1,toast:'',toastTime:0,notes:['Ночь. Оушен-Драйв пустеет, но переносное радио на причале всё ещё ловит помехи.']};checkpoint=null;
    $('sunPuzzle').hidden=true;$('sunSignal').hidden=true;$('sunPuzzleHint').textContent='Подсказки записаны в журнале.';$('sunSignalHint').textContent='Не спеши. Поймай ритм.';panel('ПОСЛЕ ЗАКАТА','Набережная у маяка. 23:47.\n\nТы возвращаешься домой, когда из старого радио доносится: «…нас сносит к скалам… маяк погас…». До высокого прилива четыре минуты.','ВЫЙТИ НА НАБЕРЕЖНУЮ ↗',()=>{save();run()});hud();draw()
  }
  function run(){halt();s.mode='running';$('sunOverlay').hidden=true;$('sunPuzzle').hidden=true;$('sunSignal').hidden=true;canvas.focus?.({preventScroll:true});last=performance.now();raf=requestAnimationFrame(frame);hud()}
  function dialogue(title,text,done,secondary){halt();s.mode='dialogue';panel(title,text,'ДАЛЬШЕ ↗',()=>{if(done)done();run()},secondary?{label:secondary.label,action:()=>{secondary.action();run()}}:null);hud();draw()}
  function notify(text){s.toast=text;s.toastTime=3}
  function blocked(x,y){const land=x>=40&&x<=1560&&y>=185&&y<=285,left=x>=270&&x<=320&&y>=265&&y<=770,right=x>=1240&&x<=1385&&y>=265&&y<=745,island=((x-1390)/135)**2+((y-790)/112)**2<=1;const tower=Math.hypot(x-1390,y-738)<44;return !(land||left||right||island)||tower}
  function move(dx,dy){const p=s.player,ox=p.x,oy=p.y;if(!blocked(p.x+dx,p.y))p.x+=dx;if(!blocked(p.x,p.y+dy))p.y+=dy;const x=p.x-ox,y=p.y-oy,d=Math.hypot(x,y);if(d>.01){p.moving=true;p.phase+=d/45*Math.PI*2;p.face=x<0?-1:x>0?1:p.face;p.heading=Math.abs(y)>Math.abs(x)*1.4?(y<0?'back':'front'):'side'}}
  function targets(){
    if(s.act===0)return [{...sites.radio,id:'radio'}];if(s.act===1)return [{...sites.keeper,id:'keeper'}];
    return [...['fuse','battery','lens'].filter(k=>!s.parts.includes(k)).map(k=>({...sites[k],id:k})),...(!s.pendant?[{...sites.pendant,id:'pendant'}]:[]),{...sites.keeper,id:'keeper'},{...sites.lighthouse,id:'lighthouse'}]
  }
  function nearest(){return targets().filter(v=>dist(v,s.player)<64).sort((a,b)=>dist(a,s.player)-dist(b,s.player))[0]}
  function interact(){
    if(s.mode!=='running')return;const target=nearest();if(!target){notify('Подойди к отмеченному объекту и нажми E.');return}
    switch(target.id){
      case 'radio':s.act=1;s.notes.push('SOS: лодка у рифов. Без маяка береговая охрана не найдёт безопасный проход.');dialogue('СИГНАЛ ИЗ ТЕМНОТЫ','«Это “Аврора”. Двигатель заглох. На борту двое. Мы видим берег, но не видим маяк…»\n\nУ основания маяка стоит смотритель. Кажется, он тоже услышал вызов.',save);break;
      case 'keeper':if(s.act===1){s.act=2;s.notes.push('Смотритель Дан: нужны предохранитель со склада, аккумулятор с дальнего пирса и линза из мастерской. На каждой детали есть число настройки.');dialogue('СМОТРИТЕЛЬ ДАН','«Шторм выбил питание. Предохранитель — у склада, аккумулятор — на дальнем пирсе, линза — у мастерской. Принеси все три.\n\nНа лодке моя сестра Лена. Она потеряла здесь медальон. Если увидишь его у края маячного пирса…»',()=>{s.promised=true;save()},{label:'СНАЧАЛА СПАСЁМ ЛОДКУ',action:()=>{s.promised=false;save()}})}else dialogue('ДАН · СМОТРИТЕЛЬ',s.pendant?'«Это её медальон… Спасибо. Теперь включи свет, я вызову береговую охрану!»':'«Склад → дальний пирс → мастерская. Числа на деталях — код пульта. Медальон ищи за маяком, у края пирса.»');break;
      case 'fuse':case 'battery':case 'lens':{
        const info={fuse:['ПРЕДОХРАНИТЕЛЬ · 07','Под крышкой складского ящика лежит целый предохранитель. На бирке выгравировано 07.'],battery:['АККУМУЛЯТОР · 12','Последний рыбацкий аккумулятор ещё держит заряд. На корпусе мелом выведено 12. Снизу слышно, как волна бьёт в сваи.'],lens:['ЛИНЗА · 03','В ящике мастерской — запасная линза маяка. Её кольцо помечено числом 03. Все подсказки сохраняются в журнале.']}[target.id];
        s.parts.push(target.id);s.notes.push(info[0]+': '+info[1]);dialogue(info[0],info[1]+(s.parts.length===3?'\n\nВсе детали найдены. Вернись к маяку и настрой три канала пульта.':''),save);break}
      case 'pendant':s.pendant=true;s.notes.push('Медальон найден за маяком. На фото Дан и Лена — ещё детьми, у этого же пирса.');dialogue('ОБЕЩАНИЕ НА БЕРЕГУ','В щели между досками блеснул медальон. На старом фото два ребёнка стоят у маяка. На обороте: «Мы всегда найдём дорогу домой».\n\nТы прячешь находку в карман.',save);break;
      case 'lighthouse':if(s.parts.length<3){notify(`Для запуска нужны все детали: найдено ${s.parts.length}/3.`);return}if(s.act===3)signal();else puzzle();break;
    }
  }
  const values=[3,7,12,19];
  function puzzle(){halt();s.mode='puzzle';$('sunOverlay').hidden=true;$('sunPuzzle').hidden=false;$('sunSignal').hidden=true;hud();draw()}
  function submit(){if(s.mode!=='puzzle')return;if(s.channels.every((v,i)=>v===[1,2,0][i])){s.act=3;s.notes.push('Пульт настроен: 07 / 12 / 03. Для передачи координат нужны три точных импульса.');save();signal()}else $('sunPuzzleHint').textContent='Пульт молчит. Сверь числа в журнале: предохранитель → аккумулятор → линза.'}
  function signal(){halt();s.mode='signal';$('sunOverlay').hidden=true;$('sunPuzzle').hidden=true;$('sunSignal').hidden=false;s.signalTime=0;s.lastPulse=-1;last=performance.now();raf=requestAnimationFrame(frame);hud();draw()}
  function pulse(){if(s.mode!=='signal'||s.signalTime-s.lastPulse<.65)return;s.lastPulse=s.signalTime;if(s.needle>=.4&&s.needle<=.62){s.pulses++;$('sunSignalHint').textContent=`Чистый импульс · ${s.pulses}/3`;}else{s.pulses=Math.max(0,s.pulses-1);s.time=Math.max(0,s.time-8);$('sunSignalHint').textContent='Помеха! −8 секунд. Нажми, когда стрелка в зелёной зоне.'}if(s.pulses>=3)win();hud()}
  function win(){halt();s.mode='over';$('sunSignal').hidden=true;const score=Math.max(0,Math.floor(s.time)*10+s.hp*150+(s.pendant?500:0));
    panel(s.pendant?'СВЕТ ВЕДЁТ ДОМОЙ':'МАЯК СНОВА ГОРИТ',s.pendant?`Луч прошёл по воде. Катер береговой охраны нашёл «Аврору» и вывел её из рифов. На причале Дан обнимает Лену. Ты возвращаешь медальон, и она улыбается: «Я знала, что он дождётся».\n\nРассвет. Хорошая концовка · ${score} очков.`:`Маяк ожил. Береговая охрана ответила: «Координаты приняты». Оба человека с «Авроры» спасены. Дан благодарит тебя и остаётся ждать сестру на причале.\n\nРассвет. Спасение состоялось · ${score} очков.\nЗа маяком осталась маленькая история — попробуй найти медальон.`, 'СЫГРАТЬ ЕЩЁ ↗',open);hud();draw()
  }
  function fail(reason){halt();s.mode='over';$('sunPuzzle').hidden=true;$('sunSignal').hidden=true;panel('НОЧЬ ЕЩЁ НЕ ЗАКОНЧЕНА',reason+'\n\nМожно вернуться к последнему сюжетному шагу с найденными деталями.', 'С ПОСЛЕДНЕГО ШАГА ↗',()=>{s=JSON.parse(JSON.stringify(checkpoint));s.hp=3;s.time=Math.max(120,s.time);s.hurt=3;run()});hud()}
  function journal(){if(s.mode==='journal'){$('sunContinue').onclick?.();return}if(!['running','puzzle','signal'].includes(s.mode))return;const prior=s.mode;halt();s.mode='journal';panel('ЖУРНАЛ НАБЕРЕЖНОЙ',s.notes.join('\n\n'),'ВЕРНУТЬСЯ ↗',()=>{if(prior==='puzzle')puzzle();else if(prior==='signal')signal();else run()});hud()}
  function pause(){if(s.mode==='paused'){$('sunContinue').onclick?.();return}if(!['running','signal','puzzle'].includes(s.mode))return;const prior=s.mode;halt();s.mode='paused';panel('ПАУЗА','Время остановлено. Найденные детали и история сохраняются.','ПРОДОЛЖИТЬ ↗',()=>{if(prior==='signal')signal();else if(prior==='puzzle')puzzle();else run()})}
  function update(dt){if(!['running','signal'].includes(s.mode))return;dt=Math.max(0,Math.min(.05,dt));s.time=Math.max(0,s.time-dt);s.elapsed+=dt;s.hurt=Math.max(0,s.hurt-dt);s.toastTime=Math.max(0,s.toastTime-dt);if(s.time<=0){fail('Прилив скрыл проход к рифам. Сигнал не успел уйти.');return}
    if(s.mode==='signal'){s.signalTime+=dt;s.needle=.5+Math.sin(s.signalTime*2.8)*.46;return}
    const p=s.player;p.moving=false;const dx=Number(held('right'))-Number(held('left')),dy=Number(held('down'))-Number(held('up')),len=Math.hypot(dx,dy)||1,sprint=held('sprint')&&s.stamina>5&&(dx||dy),speed=sprint?245:150;s.stamina=Math.max(0,Math.min(100,s.stamina+(sprint?-28:18)*dt));move(dx/len*speed*dt,dy/len*speed*dt);
    const high=s.elapsed%12>8&&s.elapsed%12<10.5;if(high&&p.y>550&&p.x<400&&s.hurt<=0){s.hp--;s.hurt=2.6;notify('Волна! Уйди с дальнего пирса или дождись отлива.');if(s.hp<=0){fail('Волны накрыли дальний пирс. Дождись, когда вода отступит, и используй рывок.');return}}
  }
  function hud(){if(!s)return;$('sunChapter').textContent=['01 · ПОМЕХИ','02 · СМОТРИТЕЛЬ','03 · ТРИ ДЕТАЛИ','04 · СИГНАЛ'][s.act];$('sunClock').textContent=`${Math.floor(s.time/60)}:${String(Math.floor(s.time%60)).padStart(2,'0')}`;$('sunParts').textContent=`${s.parts.length}/3`;$('sunHealth').textContent='♥'.repeat(s.hp)+'♡'.repeat(3-s.hp);$('sunStamina').style.width=`${s.stamina}%`;
    const t=nearest();$('sunObjective').textContent=s.toastTime>0?s.toast:s.act===0?'Найди старое радио на причале':s.act===1?'Поговори со смотрителем у маяка':s.act===3?'Передай три импульса с маяка':s.parts.length===3?'Все детали найдены → пульт маяка':'Найди предохранитель, аккумулятор и линзу';$('sunLantern').textContent=s.lantern?'F · ФОНАРЬ ВКЛ':'F · ФОНАРЬ';$('sunInteract').textContent=t?`E · ${t.label}`:'E · ОСМОТРЕТЬ';for(let i=0;i<3;i++)$('sunDial'+i).textContent=String(values[s.channels[i]]).padStart(2,'0');$('sunNeedle').style.left=`${s.needle*100}%`;$('sunPulses').textContent=`${s.pulses} / 3`;}
  function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h)}
  function label(x,y,text,color,size=11){ctx.textAlign='center';ctx.font=`bold ${size}px monospace`;ctx.fillStyle=color;ctx.fillText(text,x,y)}
  function draw(){if(!s)return;const w=canvas.clientWidth||960,h=canvas.clientHeight||540,dpr=Math.min(2,window.devicePixelRatio||1);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
    const zoom=w<600 ? .85 : Math.min(w/960,h/540),p=s.player,vw=w/zoom,vh=h/zoom,cx=Math.max(vw/2,Math.min(1600-vw/2,p.x)),cy=Math.max(vh/2,Math.min(960-vh/2,p.y));camera={zoom,x:w/2-cx*zoom,y:h/2-cy*zoom};ctx.save();ctx.translate(camera.x,camera.y);ctx.scale(zoom,zoom);ctx.imageSmoothingEnabled=false;
    if(map.complete&&map.naturalWidth)ctx.drawImage(map,0,0,1600,960);else rect(0,0,1600,960,'#132b3d');
    // Collision routes follow the painted promenade, piers and rocky island.
    const high=s.elapsed%12>8&&s.elapsed%12<10.5;for(let i=0;i<9;i++){const y=560+i*40+Math.sin(s.elapsed*2+i)*8;ctx.strokeStyle=high?'#9ef0e455':'#91d2da1a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(450,y);ctx.quadraticCurveTo(770,y-14,1120,y);ctx.stroke()}if(high){rect(270,550,50,220,'#83eee445');label(295,540,'ВОЛНА · УЙДИ К БЕРЕГУ','#fff1c2')}
    const lamp=sites.lighthouse;if(s.act<3){ctx.fillStyle='#0d213bc9';ctx.beginPath();ctx.ellipse(lamp.x,lamp.y-247,36,26,0,0,Math.PI*2);ctx.fill()}ctx.save();ctx.translate(lamp.x,lamp.y-255);ctx.rotate(s.elapsed*.27);ctx.fillStyle=s.act===3?'#ffeab435':'#ffeab409';ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,850,-.17,.17);ctx.closePath();ctx.fill();ctx.restore();
    for(const v of targets()){if(v.id==='keeper')continue;const active=v.id==='lighthouse'?s.parts.length===3:true,color=v.id==='pendant'?'#ffcfab':active?'#91eddb':'#9185a5';ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(v.x,v.y,18+Math.sin(s.elapsed*3)*2,8,0,0,Math.PI*2);ctx.stroke();if(v.id!=='lighthouse'&&v.id!=='radio'){rect(v.x-10,v.y-17,20,15,'#233543');rect(v.x-7,v.y-14,14,3,color)}label(v.x,v.y-30,v.label,color,10);if(dist(v,p)<64)label(v.x,v.y+24,'E · ДЕЙСТВИЕ','#fff1c2',10)}
    const people=[{x:sites.keeper.x,y:sites.keeper.y,id:0},{...p,id:1}];people.sort((a,b)=>a.y-b.y).forEach(a=>{ctx.fillStyle='#11162570';ctx.beginPath();ctx.ellipse(a.x,a.y+2,15,5,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(a.x,a.y);if(a.id===1&&s.hurt>0)ctx.globalAlpha=.5+Math.sin(s.elapsed*30)*.25;HumanAvatar.draw(ctx,{id:a.id,phase:a.phase||0,moving:a.id===1&&s.mode==='running'&&p.moving,heading:a.heading||'front',face:a.face||1,scale:.86,time:s.elapsed});ctx.restore();if(a.id===0)label(a.x,a.y-70,'ДАН · СМОТРИТЕЛЬ','#ffd4ac',10);else{ctx.strokeStyle='#9be8d9';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(a.x,a.y+2,18,7,0,0,Math.PI*2);ctx.stroke();label(a.x,a.y-75,'ТЫ','#c0fff0',10)}});
    ctx.restore();const lx=p.x*zoom+camera.x,ly=(p.y-30)*zoom+camera.y,light=ctx.createRadialGradient(lx,ly,70,lx,ly,s.lantern?380:260);light.addColorStop(0,'#0b122000');light.addColorStop(.65,'#0b12200a');light.addColorStop(1,'#0b122055');ctx.fillStyle=light;ctx.fillRect(0,0,w,h);
    const mx=w-140,my=12;rect(mx,my,126,82,'#101a2de3');rect(mx+3,my+3,120,24,'#565168');rect(mx+21,my+24,5,42,'#796677');rect(mx+98,my+24,12,51,'#796677');for(const v of targets()){ctx.fillStyle=v.id==='pendant'?'#ffd4ac':'#7fdfcd';ctx.fillRect(mx+v.x/1600*126-1,my+v.y/960*82-1,3,3)}ctx.fillStyle='#ff95c3';ctx.fillRect(mx+p.x/1600*126-2,my+p.y/960*82-2,4,4);label(mx+63,my+94,'НАБЕРЕЖНАЯ','#e4d9ec',9);
  }
  function frame(now){if(!['running','signal'].includes(s.mode))return;update(Math.min(.04,(now-last)/1000));last=now;hud();draw();if(['running','signal'].includes(s.mode))raf=requestAnimationFrame(frame)}
  const codes={KeyW:'up',KeyA:'left',KeyS:'down',KeyD:'right',ArrowUp:'up',ArrowLeft:'left',ArrowDown:'down',ArrowRight:'right',ShiftLeft:'sprint',ShiftRight:'sprint'},chars={w:'up',ц:'up',a:'left',ф:'left',s:'down',ы:'down',d:'right',в:'right'};
  document.addEventListener('keydown',e=>{if(game.hidden||s.mode==='closed')return;const key=(e.key||'').toLowerCase();if(['ready','dialogue','journal','paused','over'].includes(s.mode)&&(e.code==='Enter'||key==='enter'||e.code==='Space'||key===' ')){e.preventDefault();if(!e.repeat)$('sunContinue').onclick?.();return}const action=codes[e.code]||codes[e.key]||chars[key];if(action&&s.mode==='running'){e.preventDefault();inputs.set('key:'+(e.code||key),action)}if(e.repeat)return;if(e.code==='KeyE'||['e','у'].includes(key)){e.preventDefault();if(s.mode==='signal')pulse();else interact()}if(e.code==='Space'||key===' '){e.preventDefault();if(s.mode==='signal')pulse()}if(e.code==='KeyJ'||['j','о'].includes(key))journal();if(e.code==='KeyF'||['f','а'].includes(key)){if(s.mode==='running')s.lantern=!s.lantern}if(e.code==='KeyP'||['p','з'].includes(key))pause()});
  document.addEventListener('keyup',e=>inputs.delete('key:'+(e.code||(e.key||'').toLowerCase())));
  game.querySelectorAll('[data-sun-hold]').forEach(b=>{b.addEventListener('pointerdown',e=>{if(s.mode!=='running')return;e.preventDefault();b.setPointerCapture(e.pointerId);inputs.set('pointer:'+e.pointerId,b.dataset.sunHold)});['pointerup','pointercancel','lostpointercapture'].forEach(name=>b.addEventListener(name,e=>inputs.delete('pointer:'+e.pointerId)))});
  $('sunInteract').addEventListener('click',interact);$('sunJournal').addEventListener('click',journal);$('sunPause').addEventListener('click',pause);$('sunLantern').addEventListener('click',()=>{if(s.mode==='running')s.lantern=!s.lantern});
  for(let i=0;i<3;i++)$('sunDial'+i).addEventListener('click',()=>{if(s.mode==='puzzle'){s.channels[i]=(s.channels[i]+1)%4;hud()}});$('sunSubmit').addEventListener('click',submit);$('sunPuzzleJournal').addEventListener('click',journal);$('sunPuzzleBack').addEventListener('click',run);$('sunPulse').addEventListener('click',pulse);$('sunSignalBack').addEventListener('click',run);
  window.addEventListener('blur',()=>{inputs.clear();pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('resize',draw);window.addEventListener('avatarready',draw);canvas.tabIndex=0;
  window.AfterSunset={open,stop};open();
})();
