'use strict';
(()=>{
const $=s=>document.querySelector(s),canvas=$('#map'),ctx=canvas.getContext('2d'),area=$('#map-area'),data=window.LEONIDA_PLACES;
const embedded=new URLSearchParams(location.search).get('embed')==='1';let embedExpanded=false;const compact=()=>matchMedia(embedded?'(max-width:850px)':'(max-width:650px)').matches;const notifyParent=(action,extra={})=>{if(embedded&&parent!==window)parent.postMessage({type:'leonida:map',action,...extra},location.origin);};if(embedded)document.documentElement.classList.add('embedded');
const cats={all:{name:'Все кадры',color:'#ffadd6'},trailer1:{name:'Трейлер 1',color:'#f58cce'},trailer2:{name:'Трейлер 2',color:'#65d9e6'},trailer3:{name:'Extended Look',color:'#9f9dff'},screenshots:{name:'Скриншоты',color:'#ff9c8e'},el_screenshots:{name:'EL · скриншоты',color:'#ca9cf5'},bonus:{name:'Бонусные',color:'#ffc482'}};
let W=0,H=0,dpr=1,category='all',query='',selected=null,filtered=data,visibleMarkers=[],night=false,tourTimer=null,tourIndex=0;
let view={x:-3750,y:1350,s:0.03},target={...view},frame=0,lastTime=0,imageReady=false,overview=true;
const image=new Image(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const thumbnails=new Map();for(const p of data){const img=new Image();img.onload=schedule;img.src=p.thumbnail;thumbnails.set(p.id,img);}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function point(p){return {x:W/2+(p.x-view.x)*view.s,y:H/2-(p.y-view.y)*view.s};}
function world(x,y,v=view){return{x:v.x+(x-W/2)/v.s,y:v.y-(y-H/2)/v.s};}
function schedule(){if(!frame)frame=requestAnimationFrame(draw);}
function limits(){target.s=Math.min(.42,Math.max(Math.min(W/17500,H/23000)*.65,target.s));target.x=Math.max(-14500,Math.min(6000,target.x));target.y=Math.max(-11500,Math.min(13500,target.y));}
function closeDetail(){selected=null;$('#detail').hidden=true;syncSelection();schedule();}
function syncSelection(){for(const row of $('#places').querySelectorAll('.place-row')){const active=row.dataset.id===selected?.id;row.classList.toggle('active',active);row.setAttribute('aria-pressed',String(active));}}
function setMenu(open){$('.atlas').classList.toggle('menu-open',open);$('#menu').setAttribute('aria-expanded',String(open));$('#sidebar').inert=compact()&&!open;}
function closeMenu(){setMenu(false);}
function fit(){stopTour();overview=true;closeDetail();closeMenu();target={x:-3750,y:1350,s:Math.min(W/15800,H/20500)*.92};limits();if(reduced)view={...target};schedule();renderList();}
function resize(){const r=area.getBoundingClientRect();W=r.width;H=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(overview){target.s=Math.min(W/15800,H/20500)*.92;view={...target};}setMenu($('.atlas').classList.contains('menu-open'));if(selected)focusPlace(selected);limits();schedule();}
function draw(time){frame=0;const dt=Math.min(48,time-lastTime||16);lastTime=time;const ease=reduced?1:1-Math.exp(-dt/85);view.x+=(target.x-view.x)*ease;view.y+=(target.y-view.y)*ease;view.s+=(target.s-view.s)*ease;ctx.clearRect(0,0,W,H);ctx.fillStyle='#2c67a4';ctx.fillRect(0,0,W,H);
 ctx.save();ctx.filter=night?'brightness(.72) saturate(.75)':'none';
 if(imageReady){const origin=point({x:-16384,y:16384});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(image,0,0,2500,4096,origin.x,origin.y,20000*view.s,32768*view.s);}
 drawDetailTiles(time);ctx.restore();
 // Stable dataset order and constant marker size: no screen-grid or zoom thresholds.
 visibleMarkers=[];for(const p of filtered){if(p.id!==selected?.id)paintMarker(p,false);}if(selected&&filtered.includes(selected))paintMarker(selected,true);
 const targetPixels=1000*view.s;const scale=targetPixels<40?2000:targetPixels>140?500:1000;$('#scale-label').textContent=scale>=1000?scale/1000+' км':scale+' м';$('#scale-line').style.width=Math.round(scale*view.s)+'px';
 if(Math.abs(target.x-view.x)>.25||Math.abs(target.y-view.y)>.25||Math.abs(target.s-view.s)>.0000005)schedule();
}
const tileIndex=new Set((window.LEONIDA_TILES||[]).map(([y,x])=>`${y}-${x}`)),tileCache=new Map();let tileActive=0,tileQueue=[];
function pumpTiles(){while(tileActive<6&&tileQueue.length){const entry=tileQueue.shift();if(entry.state!=='queued')continue;entry.state='loading';tileActive++;const img=new Image();entry.img=img;img.onload=()=>{tileActive--;entry.state='ready';entry.ready=performance.now();schedule();pumpTiles();};img.onerror=()=>{tileActive--;entry.state='error';entry.retry=performance.now()+30000;schedule();pumpTiles();};img.src=entry.url;}}
function drawDetailTiles(time){
 const density=view.s*dpr;if(density<.125){tileQueue=[];for(const [key,e]of tileCache)if(e.state==='queued')tileCache.delete(key);return;}
 const size=density>.5?1024:density>.25?512:256,topLeft=world(0,0),bottomRight=world(W,H);
 const minX=Math.max(0,Math.floor((topLeft.x+16384)/1024)),maxX=Math.min(19,Math.floor((bottomRight.x+16384)/1024));
 const minY=Math.max(0,Math.floor((16384-topLeft.y)/1024)),maxY=Math.min(31,Math.floor((16384-bottomRight.y)/1024));
 const needed=new Set();let pending=0;ctx.save();const origin=point({x:-16384,y:16384});ctx.beginPath();ctx.rect(origin.x,origin.y,20000*view.s,32768*view.s);ctx.clip();
 for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){
  const id=`${y}-${x}`;if(!tileIndex.has(id))continue;const key=`${size}/${id}`;needed.add(key);let entry=tileCache.get(key);
  if(!entry||(entry.state==='error'&&time>entry.retry)){entry={state:'queued',size,url:`assets/detail/${size}/${id}.webp`,used:time};tileCache.set(key,entry);}
  entry.used=time;const pos=point({x:x*1024-16384,y:16384-y*1024});const left=Math.round(pos.x*dpr)/dpr,top=Math.round(pos.y*dpr)/dpr,right=Math.round((pos.x+1024*view.s)*dpr)/dpr,bottom=Math.round((pos.y+1024*view.s)*dpr)/dpr;
  for(const lower of [256,512,1024]){const fallback=tileCache.get(`${lower}/${id}`);if(fallback?.state!=='ready')continue;if(lower<=size)fallback.used=time;ctx.globalAlpha=Math.min(1,(time-fallback.ready)/160);ctx.drawImage(fallback.img,left,top,right-left,bottom-top);if(ctx.globalAlpha<1)schedule();}ctx.globalAlpha=1;
  if(entry.state!=='ready'&&entry.state!=='error')pending++;
 }
 ctx.restore();
 tileQueue=[];for(const [key,e]of tileCache){if(e.state==='queued'){if(needed.has(key))tileQueue.push(e);else tileCache.delete(key);}}
 tileQueue.sort((a,b)=>{const coords=e=>e.url.match(/(\d+)-(\d+)\.webp$/).slice(1).map(Number);const [ay,ax]=coords(a),[by,bx]=coords(b);return Math.hypot(ax-(minX+maxX)/2,ay-(minY+maxY)/2)-Math.hypot(bx-(minX+maxX)/2,by-(minY+maxY)/2);});pumpTiles();
 let bytes=[...tileCache.values()].reduce((n,e)=>n+(e.state==='ready'?e.size*e.size*4:0),0);
 for(const [key,e]of [...tileCache].sort((a,b)=>a[1].used-b[1].used)){if(bytes<64*1024*1024)break;if(e.state==='ready'&&!needed.has(key)&&time-e.used>2000){bytes-=e.size*e.size*4;e.img.src='';tileCache.delete(key);}}
 canvas.dataset.detail=pending?'loading':'ready';
}

function paintMarker(p,isSelected){const pos=point(p),r=15;const cat=cats[p.category];visibleMarkers.push({...pos,p});ctx.save();
 if(isSelected){ctx.beginPath();ctx.arc(pos.x,pos.y,22,0,Math.PI*2);ctx.strokeStyle='#ffd0e8';ctx.lineWidth=2;ctx.stroke();}
 ctx.shadowColor='#07152cb3';ctx.shadowBlur=5;ctx.beginPath();ctx.arc(pos.x,pos.y,r,0,Math.PI*2);ctx.fillStyle='#14223b';ctx.fill();ctx.shadowBlur=0;
 const img=thumbnails.get(p.id);if(img?.complete&&img.naturalWidth){ctx.save();ctx.beginPath();ctx.arc(pos.x,pos.y,r-1,0,Math.PI*2);ctx.clip();const ratio=Math.max(30/img.naturalWidth,30/img.naturalHeight);ctx.drawImage(img,pos.x-img.naturalWidth*ratio/2,pos.y-img.naturalHeight*ratio/2,img.naturalWidth*ratio,img.naturalHeight*ratio);ctx.restore();}else{ctx.fillStyle=cat.color;ctx.font='16px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('▣',pos.x,pos.y);}
 ctx.beginPath();ctx.arc(pos.x,pos.y,r,0,Math.PI*2);ctx.strokeStyle=isSelected?'#fff':cat.color;ctx.lineWidth=isSelected?3:2;ctx.stroke();
 if(isSelected){ctx.font='600 12px Manrope,Arial';const name=p.name;const w=Math.min(280,ctx.measureText(name).width+18);const x=Math.max(6,Math.min(W-w-80,pos.x-w/2));ctx.fillStyle='#121e32f5';ctx.beginPath();ctx.roundRect(x,pos.y+25,w,27,5);ctx.fill();ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(name,x+w/2,pos.y+38,w-16);}
 ctx.restore();}

function renderList(){const list=$('#places');$('#count').textContent=filtered.length;list.replaceChildren();if(!filtered.length){const e=document.createElement('p');e.className='empty';e.textContent='Кадров не найдено. Попробуй другое название или источник.';list.append(e);return;}
 const fragment=document.createDocumentFragment();filtered.forEach((p,i)=>{const b=document.createElement('button');b.className='place-row'+(selected?.id===p.id?' active':'');b.dataset.id=p.id;b.style.setProperty('--accent',cats[p.category].color);b.innerHTML=`<img class="frame-thumb" src="${escape(p.thumbnail)}" alt="" loading="lazy" width="64" height="40"><span class="place-copy"><span class="place-name">${escape(p.name)}</span><span class="place-region">${escape(p.frame||cats[p.category].name)} · ${escape(p.region||'Леонида')}</span></span><span class="place-index">${String(i+1).padStart(2,'0')}</span>`;b.addEventListener('click',()=>select(p));fragment.append(b);});list.append(fragment);
}
function applyFilters(){stopTour();query=$('#search').value.trim().toLocaleLowerCase();filtered=data.filter(p=>(category==='all'||p.category===category)&&(!query||([p.name,p.address,p.region,p.frame,p.id].join(' ')).toLocaleLowerCase().includes(query)));if(selected&&!filtered.includes(selected)){selected=null;$('#detail').hidden=true;}renderList();schedule();}
function focusPlace(p){target.x=p.x;target.y=p.y;const h=$('#detail').getBoundingClientRect().height;if(!compact()||(H<500&&W>500)){const cardWidth=$('#detail').getBoundingClientRect().width+(!compact()?26:12);target.x-=(Math.max(W/2,(cardWidth+W-65)/2)-W/2)/target.s;}else target.y+=(Math.max(110,(H-h-47+75)/2)-H/2)/target.s;limits();}
function select(p,fromTour=false){if(!fromTour)stopTour();overview=false;selected=p;target.s=Math.max(.10,Math.min(.20,Math.min(W,H)/3600));target.x=p.x;target.y=p.y;limits();$('#detail').hidden=false;$('#detail').innerHTML=`<button class="detail-close" aria-label="Закрыть кадр">×</button><button class="frame-preview" aria-label="Открыть скриншот крупно"><img src="${escape(p.image)}" alt="${escape(p.name)} — игровой кадр GTA VI" width="1920" height="1080"><span>⛶</span></button><div class="detail-body"><div class="detail-meta"><span class="badge">${cats[p.category].name}</span><span class="detail-id">${escape(p.frame||p.id)}</span></div><h2>${escape(p.name)}</h2><p>${escape(p.region||'Леонида')}${p.uncertain?' · Предположительное положение':''}</p><div class="frame-credit">${escape(p.credit)}</div><a class="detail-link" target="_blank" rel="noopener" href="${escape(p.source)}">Источник: State of Leonida</a><div class="coords">X ${Math.round(p.x)} &nbsp; Y ${Math.round(p.y)}</div></div>`;$('.detail-close').onclick=closeDetail;$('.frame-preview').onclick=()=>openFrame(p);syncSelection();closeMenu();focusPlace(p);schedule();}
function openFrame(p){stopTour();const dialog=$('#frame-dialog');dialog.innerHTML=`<button class="frame-dialog-close" aria-label="Закрыть скриншот">×</button><img src="${escape(p.image)}" alt="${escape(p.name)} — игровой кадр GTA VI"><div class="frame-dialog-caption"><div><strong>${escape(p.name)}</strong><span>${cats[p.category].name} · ${escape(p.frame||p.id)} · ${escape(p.credit)}</span></div><a href="${escape(p.sourceImage)}" target="_blank" rel="noopener">Оригинал</a></div>`;dialog.querySelector('button').onclick=()=>dialog.close();dialog.showModal();}

function zoom(f,x,y){if(x===undefined)x=selected?W/2+(selected.x-target.x)*target.s:W/2;if(y===undefined)y=selected?H/2-(selected.y-target.y)*target.s:H/2;overview=false;const before=world(x,y,target);target.s*=f;limits();target.x=before.x-(x-W/2)/target.s;target.y=before.y+(y-H/2)/target.s;limits();schedule();}
function nearest(x,y){let best=null;for(let i=visibleMarkers.length-1;i>=0;i--){const m=visibleMarkers[i],d=Math.hypot(x-m.x,y-m.y);if(d<23&&(!best||d<best.d-.01))best={...m,d};}return best;}
const pointers=new Map();let gesture=null,moved=false;
canvas.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;stopTour();overview=false;canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});if(pointers.size===1)moved=false;else moved=true;target={...view};beginGesture();$('#tip').hidden=true;});
function beginGesture(){const ps=[...pointers.values()];if(ps.length>=2){const a=ps[0],b=ps[1];gesture={type:'pinch',d:Math.hypot(a.x-b.x,a.y-b.y),center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},view:{...target}};}else if(ps.length)gesture={type:'pan',start:ps[0],view:{...target}};else gesture=null;}
canvas.addEventListener('pointermove',e=>{if(pointers.has(e.pointerId)){pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});const ps=[...pointers.values()];if(gesture?.type==='pan'&&embedded&&!embedExpanded&&e.pointerType==='touch'){const delta=gesture.start.y-ps[0].y;gesture.distance=(gesture.distance||0)+Math.hypot(ps[0].x-gesture.start.x,delta);moved ||= gesture.distance>5;gesture.start=ps[0];notifyParent('scroll',{delta});return;}if(gesture?.type==='pan'){const dx=ps[0].x-gesture.start.x,dy=ps[0].y-gesture.start.y;moved ||= Math.hypot(dx,dy)>5;target.x=gesture.view.x-dx/gesture.view.s;target.y=gesture.view.y+dy/gesture.view.s;}else if(gesture?.type==='pinch'&&ps.length>=2){moved=true;const d=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y),c={x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2};const w=world(gesture.center.x,gesture.center.y,gesture.view);target.s=gesture.view.s*d/Math.max(gesture.d,1);limits();target.x=w.x-(c.x-W/2)/target.s;target.y=w.y+(c.y-H/2)/target.s;}limits();view={...target};schedule();return;}
 const n=nearest(e.offsetX,e.offsetY);canvas.style.cursor=n?'pointer':'grab';const tip=$('#tip');tip.hidden=!n;if(n){tip.textContent=n.p.name;tip.style.left=Math.min(W-200,Math.max(10,n.x+18))+'px';tip.style.top=Math.max(75,n.y-15)+'px';}});
canvas.addEventListener('pointerup',e=>{if(!pointers.has(e.pointerId))return;const wasPinch=gesture?.type==='pinch';pointers.delete(e.pointerId);if(!moved&&!wasPinch){const n=nearest(e.offsetX,e.offsetY);if(n)select(n.p);}beginGesture();});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);beginGesture();});canvas.addEventListener('pointerleave',()=>$('#tip').hidden=true);
canvas.addEventListener('wheel',e=>{e.preventDefault();if(embedded&&!embedExpanded&&!e.ctrlKey&&!e.metaKey){notifyParent('scroll',{delta:e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?H:1)});return;}stopTour();zoom(Math.exp(-Math.max(-200,Math.min(200,e.deltaY))*.002),e.offsetX,e.offsetY);},{passive:false});
canvas.addEventListener('dblclick',e=>zoom(1.7,e.offsetX,e.offsetY));
canvas.addEventListener('keydown',e=>{const a={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,1],ArrowDown:[0,-1]}[e.key];if(a){e.preventDefault();stopTour();overview=false;target.x+=a[0]*100/target.s;target.y+=a[1]*100/target.s;limits();schedule();}if(e.key==='+'||e.key==='='||e.key==='-'){e.preventDefault();stopTour();zoom(e.key==='-'?1/1.4:1.4);}});
$('#zoom-in').onclick=()=>{stopTour();zoom(1.5);};$('#zoom-out').onclick=()=>{stopTour();zoom(1/1.5);};$('#reset').onclick=fit;$('.brand').onclick=e=>{e.preventDefault();fit();};
$('#fullscreen').onclick=async()=>{if(embedded){notifyParent('expand');return;}try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('#fullscreen').title='Полный экран недоступен в этом режиме';}};
document.addEventListener('fullscreenchange',()=>$('#fullscreen').setAttribute('aria-label',document.fullscreenElement?'Выйти из полного экрана':'Полный экран'));
$('#search').addEventListener('input',applyFilters);document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.target.closest('input,textarea,[contenteditable],dialog')){e.preventDefault();setMenu(true);$('#search').focus();}if(e.key==='Escape'&&!document.querySelector('dialog[open]')){if(embedded&&embedExpanded){notifyParent('collapse');return;}stopTour();if($('.atlas').classList.contains('menu-open'))closeMenu();else closeDetail();}});
Object.entries(cats).forEach(([id,c])=>{const b=document.createElement('button');b.textContent=c.name;b.dataset.category=id;b.className=id===category?'active':'';b.setAttribute('aria-pressed',id===category?'true':'false');b.onclick=()=>{category=id;$('#filters').querySelectorAll('button').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-pressed',String(n===b));});applyFilters();};$('#filters').append(b);});
for(const mode of ['day','night'])$('#'+mode).onclick=()=>{night=mode==='night';area.classList.toggle('night',night);$('#day').classList.toggle('active',!night);$('#night').classList.toggle('active',night);$('#day').setAttribute('aria-pressed',String(!night));$('#night').setAttribute('aria-pressed',String(night));schedule();};
$('#menu').onclick=()=>setMenu(!$('.atlas').classList.contains('menu-open'));
$('#about').onclick=()=>{stopTour();$('#about-dialog').showModal();};$('.dialog-close').onclick=()=>$('#about-dialog').close();for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
const stops=['trailer1_001','trailer1_002','trailer2_004','screenshots_001','trailer3_001','el_screenshots-screenshots_041'].map(id=>data.find(p=>p.id===id)).filter(Boolean);
function stopTour(){clearTimeout(tourTimer);tourTimer=null;$('#tour').classList.remove('running');$('#tour').innerHTML='<span>▷</span> Обзор кадров';}
function tourStep(){if(!stops.length){stopTour();return;}select(stops[tourIndex++%stops.length],true);tourTimer=setTimeout(tourStep,5500);}
$('#tour').onclick=()=>{if(tourTimer){stopTour();return;}category='all';$('#search').value='';$('#filters button[data-category="all"]').click();tourIndex=0;$('#tour').classList.add('running');$('#tour').innerHTML='<span>Ⅱ</span> Остановить';tourStep();};
window.addEventListener('message',e=>{if(!embedded||e.origin!==location.origin||e.source!==parent||e.data?.type!=='leonida:host')return;if(e.data.action==='expanded'){embedExpanded=e.data.value===true;document.documentElement.classList.toggle('embedded-expanded',embedExpanded);$('.map-hint').textContent=embedExpanded?'Колесо — масштаб · Перетаскивай карту':(/Mac/.test(navigator.platform)?'⌘':'Ctrl')+' + колесо — масштаб · Перетаскивай карту';$('#fullscreen').setAttribute('aria-label',embedExpanded?'Свернуть карту':'Развернуть карту');}if(e.data.action==='active'&&e.data.value===false)stopTour();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTour();});
if(embedded){$('.mobile-scroll-hint').hidden=false;$('.map-hint').textContent=(/Mac/.test(navigator.platform)?'⌘':'Ctrl')+' + колесо — масштаб · Перетаскивай карту';}
new ResizeObserver(resize).observe(area);image.onload=()=>{imageReady=true;$('#loading').hidden=true;notifyParent('ready');schedule();};image.onerror=()=>{$('#loading').textContent='Не удалось загрузить карту. Обнови страницу.';};image.src='assets/leonida.webp';resize();applyFilters();
// Expose the same navigation action when the browser supports WebMCP.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'open_leonida_place',title:'Открыть место на карте',description:'Приблизить карту к кадру State of Leonida и открыть игровой скриншот.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.id!=='string')throw new Error('Нужен строковый id места');const p=data.find(p=>p.id===input.id);if(!p)throw new Error('Место не найдено');category='all';$('#search').value='';$('#filters button[data-category="all"]').click();select(p);return{id:p.id,name:p.name,x:p.x,y:p.y,image:p.image};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
